### ISSUE TITLE
Store data in a database format (not flat-file JSONs)

### ISSUE THREAD

**Issue by louh** [codeforamerica/naics-api#10]
pinging @daguar @rclosner @ycombinator for recommendations.

**Comment by lovehandle** [comment]
Not a bad idea, but I would like to hear the reasoning why. Dependent upon what you're looking to do, it might make more sense to keep the API reliant upon flat JSON files.

**Comment by ycombinator** [comment]
+1 @rclosner. What's the use case? That should drive the technology decision.

**Comment by louh** [comment]
Briefly mentioned in a discussion here:
https://github.com/dobtco/NAICS/issues/1

So far the flat version works fine, but I was under the impression that if
it got too large then having a database is the way to go for speed, etc. I
thought I could head it off by getting it started early, but I'm okay with
not doing this until someone who knows more about this than I do points out
when/if it is necessary.

On Tue, Jun 4, 2013 at 5:17 PM, Shaunak Kashyap notifications@github.comwrote:

> +1 @rclosner https://github.com/rclosner. What's the use case? That
> should drive the technology decision.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/louh/naics-api/issues/10#issuecomment-18948084
> .

## 

_Lou Huang_
2013 Fellow, Code for America / San Francisco / Las Vegas
lou@codeforamerica.org | 510.364.0641 | @saikofishhttp://twitter.com/saikofish
 | louhuang.com http://www.louhuang.com/

**Comment by daguar** [comment]
#YAGNI

**Comment by louh** [comment]
I had to look that up.

Thanks, everyone.
