### ISSUE TITLE
Implement CORS support

### ISSUE THREAD

**Issue by daguar** [codeforamerica/naics-api#13]
I left some thoughts in Campfire, but this post shows how to implement CORS support on a NodeJS server:
http://senecacd.wordpress.com/2013/02/15/enabling-cors-on-a-node-js-server-same-origin-policy-issue/

CORS is all about serving with the appropriate headers; nothing is required on the client side beyond making a normal AJAX request across domains to test.

**Comment by louh** [comment]
Solved w/ help from http://stackoverflow.com/questions/14338683/how-can-i-support-cors-when-using-restify
